/**
 * mockDiagnostic loader (#492 Slice 3.6)
 *
 * Surfaces the learner's most recent post-Mock diagnostic into the next-call
 * composition so the tutor can guide the conversation toward the focus
 * modules / strength / weak skill that came out of the Mock.
 *
 * The diagnostic is produced by `generateDiagnosticFromMock` (#494 E2
 * Slice 2.6) and persisted by `writeDiagnosticFromMock` in the AGGREGATE
 * stage as a single `CallerAttribute` row keyed by
 * `(callerId, key="fromMock", scope="DIAGNOSTIC")`. The upsert means there
 * is ordinarily exactly one row — but we still order by `updatedAt desc`
 * defensively so future writers that prefer insert-then-clean cannot
 * surprise this loader.
 *
 * Wire-up:
 *   - dataSource : "mockDiagnostic"
 *   - transform  : "renderMockDiagnostic"
 *   - outputKey  : "mockDiagnostic"
 *   - activation : "mockDiagnosticExists" (hasDiagnostic === true)
 *   - fallback   : { action: "omit" }
 *
 * Safety:
 *   - All failure paths return `hasDiagnostic: false`. The SectionDataLoader
 *     wrapper additionally try/catches so a slow/broken DIAGNOSTIC row
 *     never breaks composition.
 *   - When `fromCallId === currentCallId` the diagnostic is the SAME call
 *     we are composing for — emitting it would create a chicken/egg loop
 *     (the tutor referencing a Mock the learner hasn't yet finished from
 *     their perspective). Suppressed.
 *   - Deleted modules are dropped from `focusModules` and zeroed out for
 *     `strengthModule` rather than crashing the section.
 *
 * @see lib/curriculum/diagnostic-from-mock.ts (generator)
 * @see app/api/calls/[callId]/pipeline/route.ts::writeDiagnosticFromMock
 * @see transforms/mockDiagnostic.ts (renderer)
 */

import type { PrismaClient } from "@prisma/client";

export interface MockDiagnosticModuleRef {
  id: string;
  slug: string;
  title: string;
}

export interface MockDiagnosticData {
  hasDiagnostic: boolean;
  focusModules: MockDiagnosticModuleRef[];
  strengthModule: MockDiagnosticModuleRef | null;
  weakSkill: string | null;
  summary: string | null;
  fromCallId: string | null;
  /** ISO-8601 timestamp from the diagnostic JSON. */
  generatedAt: string | null;
  /** Floor((now - generatedAt) / 86400000). Null when generatedAt missing. */
  ageInDays: number | null;
}

export interface LoadMockDiagnosticOptions {
  callerId: string;
  /** Current call id — used to skip the diagnostic generated by THIS call. */
  currentCallId: string;
  /** Override "now" for deterministic tests. */
  now?: Date;
}

const EMPTY: MockDiagnosticData = {
  hasDiagnostic: false,
  focusModules: [],
  strengthModule: null,
  weakSkill: null,
  summary: null,
  fromCallId: null,
  generatedAt: null,
  ageInDays: null,
};

/**
 * Subset of PrismaClient used by this loader — narrows the surface so tests
 * can pass a minimal mock object.
 */
type PrismaForLoader = Pick<PrismaClient, "callerAttribute" | "curriculumModule">;

/**
 * Shape of the serialised diagnostic written to `CallerAttribute.stringValue`.
 * Mirrors `DiagnosticFromMock` from `lib/curriculum/diagnostic-from-mock.ts`
 * — duplicated here as a local interface so this loader is self-contained
 * and not coupled to the writer module.
 */
interface SerialisedDiagnostic {
  focusModules: string[];
  strengthModule: string | null;
  weakSkill: string | null;
  summary: string;
  fromCallId: string;
  generatedAt: string;
}

/**
 * Load the most recent post-Mock diagnostic for `callerId`, resolving the
 * raw module IDs into `{ id, slug, title }` triples for prompt-friendly
 * rendering. Returns the empty shape when:
 *
 *   - `callerId` is missing
 *   - No DIAGNOSTIC/fromMock row exists
 *   - The row's `stringValue` is missing or fails JSON.parse
 *   - The diagnostic was produced BY the call we are composing for
 */
export async function loadMockDiagnostic(
  prisma: PrismaForLoader,
  opts: LoadMockDiagnosticOptions,
): Promise<MockDiagnosticData> {
  const { callerId, currentCallId, now } = opts;
  if (!callerId) return EMPTY;

  // 1. Pull the most recent DIAGNOSTIC/fromMock row. The unique constraint
  // (`@@unique([callerId, key, scope])`) means there's only ever one row,
  // but ordering by updatedAt desc is defensive.
  const row = await prisma.callerAttribute.findFirst({
    where: {
      callerId,
      scope: "DIAGNOSTIC",
      key: "fromMock",
    },
    orderBy: { updatedAt: "desc" },
    select: { stringValue: true, updatedAt: true },
  });

  if (!row || !row.stringValue) return EMPTY;

  // 2. Parse the JSON payload. A parse failure means the writer is broken
  // or someone hand-edited the DB — log and silently drop the section
  // rather than poison the prompt.
  let parsed: SerialisedDiagnostic;
  try {
    parsed = JSON.parse(row.stringValue) as SerialisedDiagnostic;
  } catch (err) {
    console.warn(
      "[mockDiagnostic] Failed to parse CallerAttribute.stringValue — omitting section:",
      err instanceof Error ? err.message : String(err),
    );
    return EMPTY;
  }

  // 3. Chicken/egg skip — if the diagnostic was generated by the current
  // call, the learner has not yet "received" it from their POV. Surface
  // it on the NEXT call instead.
  if (parsed.fromCallId && currentCallId && parsed.fromCallId === currentCallId) {
    return EMPTY;
  }

  // 4. Resolve module IDs → { id, slug, title } triples. One DB roundtrip
  // for both focus + strength. Missing rows are dropped from focus and
  // zeroed out for strength (rather than emitting a broken reference).
  const idsToFetch = new Set<string>(parsed.focusModules ?? []);
  if (parsed.strengthModule) idsToFetch.add(parsed.strengthModule);

  let modulesById = new Map<string, MockDiagnosticModuleRef>();
  if (idsToFetch.size > 0) {
    const rows = await prisma.curriculumModule.findMany({
      where: { id: { in: Array.from(idsToFetch) } },
      select: { id: true, slug: true, title: true },
    });
    modulesById = new Map(
      rows.map((m) => [m.id, { id: m.id, slug: m.slug, title: m.title }]),
    );
  }

  const focusModules: MockDiagnosticModuleRef[] = (parsed.focusModules ?? [])
    .map((id) => modulesById.get(id))
    .filter((m): m is MockDiagnosticModuleRef => m !== undefined);

  const strengthModule: MockDiagnosticModuleRef | null = parsed.strengthModule
    ? modulesById.get(parsed.strengthModule) ?? null
    : null;

  // 5. Compute age in days from generatedAt. floor() because "2.6 days ago"
  // is more naturally read as "2 days ago" in the prompt.
  const generatedAtMs = parsed.generatedAt ? Date.parse(parsed.generatedAt) : NaN;
  const ageInDays = Number.isFinite(generatedAtMs)
    ? Math.floor(((now ?? new Date()).getTime() - generatedAtMs) / 86_400_000)
    : null;

  return {
    hasDiagnostic: true,
    focusModules,
    strengthModule,
    weakSkill: parsed.weakSkill ?? null,
    summary: parsed.summary ?? null,
    fromCallId: parsed.fromCallId ?? null,
    generatedAt: parsed.generatedAt ?? null,
    ageInDays,
  };
}
