/**
 * generate-writer-coverage-doc.ts (#1619 / Epic #1618 Slice 2)
 *
 * Generates `docs/writer-coverage.md` from the `WRITER_REGISTRY` const
 * so reviewers + auditors can see the full reader↔writer pairing
 * surface in one place without reading TypeScript.
 *
 * Run via: `npx tsx apps/admin/scripts/generate-writer-coverage-doc.ts`
 *
 * Conservative regeneration — only overwrites `docs/writer-coverage.md`.
 * CI guard could compare the generated output to the committed file
 * and fail on drift; not yet wired but the file is deterministic
 * enough for that test to land in a follow-up.
 */

import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { WRITER_REGISTRY } from "../lib/contracts/writer-registry";

const REPO_ROOT = resolve(__dirname, "../../..");
const TARGET = join(REPO_ROOT, "docs/writer-coverage.md");

const lines: string[] = [];

lines.push("# Writer Coverage");
lines.push("");
lines.push(
  "> Generated by `apps/admin/scripts/generate-writer-coverage-doc.ts` from `apps/admin/lib/contracts/writer-registry.ts`. Do not edit by hand — re-run the generator after registry changes.",
);
lines.push("");
lines.push(
  "Pairs every nullable Prisma field that has a UI/API reader with the writer function + pipeline stage + invocation trigger that's expected to populate it. The arch-checker integration (`check-writer-registry.ts`) validates these pairings at PR time so a reader added without a registered writer fails CI before reaching production.",
);
lines.push("");
lines.push("**Maintenance contract:** see the JSDoc on `WRITER_REGISTRY` in `writer-registry.ts`.");
lines.push("");

lines.push("## Coverage by stage");
lines.push("");
const byStage = new Map<string, typeof WRITER_REGISTRY[number][]>();
for (const e of WRITER_REGISTRY) {
  const bucket = byStage.get(e.stage) ?? [];
  bucket.push(e);
  byStage.set(e.stage, bucket);
}

for (const [stage, entries] of [...byStage.entries()].sort()) {
  lines.push(`### ${stage}`);
  lines.push("");
  lines.push("| Field | Writer | Reader | Trigger | Closed by |");
  lines.push("|---|---|---|---|---|");
  for (const e of entries) {
    lines.push(
      `| \`${e.field}\` | \`${e.writer}\` | \`${e.reader}\` | ${e.expectedTrigger} | ${e.closedBy} |`,
    );
  }
  lines.push("");
  for (const e of entries) {
    lines.push(`- **${e.field}** — ${e.description}`);
  }
  lines.push("");
}

lines.push("## Full row dump");
lines.push("");
lines.push("```json");
lines.push(JSON.stringify(WRITER_REGISTRY, null, 2));
lines.push("```");
lines.push("");

writeFileSync(TARGET, lines.join("\n") + "\n");
console.log(`✓ writer-coverage doc generated → ${TARGET}`);
console.log(`  ${WRITER_REGISTRY.length} entries across ${byStage.size} stage(s).`);
