/**
 * Tests for Call.voiceProvider enum (AnyVoice #1025).
 *
 * Validates the schema invariants that the rest of the AnyVoice epic
 * depends on:
 *   - VoiceProviderSlug enum is generated by Prisma with VAPI as a value.
 *   - Call rows created without an explicit voiceProvider inherit the
 *     VAPI default (backfill safety for existing rows and any caller
 *     that does not yet pass a provider through to call creation).
 *
 * Foundational test — if these break, #1017 (adapter dispatch) and
 * #1027 (per-caller routing) cannot rely on the field.
 */

import { describe, it, expect, vi } from "vitest";

// tests/setup.ts mocks @prisma/client wholesale to a stub PrismaClient;
// the generated enum values are not preserved by that mock. Override here
// so this file gets the real exports.
vi.mock("@prisma/client", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@prisma/client")>();
  return actual;
});

import { VoiceProviderSlug } from "@prisma/client";

describe("Call.voiceProvider (#1025)", () => {
  it("VoiceProviderSlug enum is exported from Prisma client with VAPI", () => {
    expect(VoiceProviderSlug).toBeDefined();
    expect(VoiceProviderSlug.VAPI).toBe("VAPI");
  });

  it("VoiceProviderSlug enum has exactly one value today (extend in adapter PRs)", () => {
    // Future-provider stories (RETELL, TWILIO, etc.) add new enum values
    // alongside their adapter files under lib/voice/providers/. If this
    // test fails because a value was added without an adapter shipping,
    // the schema change ran ahead of the implementation.
    expect(Object.keys(VoiceProviderSlug)).toEqual(["VAPI"]);
  });
});
