/**
 * AnalysisSpec writer — #829 (Story 5 of EPIC #832).
 *
 * Central enforcement point for writes to compose-affecting AnalysisSpec
 * fields. The bump target depends on the spec's `scope`:
 *
 *   - `SYSTEM`  → upsert `SystemSetting` key `"compose_inputs_updated_at"`
 *                 (ISO string). Read by `isPromptStale` for every caller —
 *                 marks the whole system stale until the next compose runs
 *                 per caller. Use for INIT-001 / global guardrail edits.
 *   - `DOMAIN`  → bump `Domain.composeInputsUpdatedAt` for the spec's
 *                 owning domain. Requires `options.domainId` since the
 *                 schema has no direct `AnalysisSpec.domainId` FK.
 *                 If `domainId` is omitted on a DOMAIN-scope write, the
 *                 helper logs a warning and skips the bump (safe fallback
 *                 — downstream callers will be served the cached prompt
 *                 until some other write marks them stale).
 *   - `CALLER`  → no-op. CALLER-scope specs are auto-generated by the
 *                 system and never mutated through admin tools; mutating
 *                 their config does not flow into composition.
 *
 * Blast radius:
 *   - SYSTEM scope: every caller in every playbook in every domain. This
 *     is the correct behaviour for an INIT-001 config change. The spike
 *     of recompose work is bounded by the call rate (each caller
 *     recomposes once on its next call) and is therefore self-rate-limited.
 *   - DOMAIN scope: every caller in every playbook in this domain. Same
 *     blast radius as `updateDomainConfig` (Story 4 #828).
 *   - CALLER scope: no bump.
 *
 * Mechanism — stamp on write, lazy recompose on read (per
 * `docs/CHAIN-CONTRACTS.md` §3 Link 3 sub-contract):
 *
 *   1. findUnique current AnalysisSpec row (scope + compose-affecting fields)
 *   2. apply transformer to a deep clone
 *   3. diff against COMPOSE_AFFECTING_SPEC_FIELDS
 *   4. write new fields; if any compose-affecting field changed AND
 *      `skipTimestamp` is not set, bump the scope-appropriate timestamp
 *      target
 *
 * The ESLint rule `hf-spec/no-direct-config-write` blocks direct
 * `prisma.analysisSpec.update({data:{config|promptTemplate|...:...}})`
 * outside this helper + allowlist (seeds, scripts, recompile route,
 * trigger metadata routes).
 *
 * `skipTimestamp: true` is for seed scripts / pre-enrolment paths where
 * no callers exist yet.
 */

import { prisma } from "@/lib/prisma";
import type { AnalysisSpec, Prisma, SpecificationScope } from "@prisma/client";
import {
  composeAffectingSpecChanged,
  COMPOSE_AFFECTING_SPEC_FIELDS,
} from "@/lib/compose/affecting-keys-spec";
import { SYSTEM_COMPOSE_TIMESTAMP_KEY } from "@/lib/compose/staleness";

/** Subset of AnalysisSpec that this helper is allowed to mutate. */
export type AnalysisSpecUpdatable = Partial<Pick<
  AnalysisSpec,
  | "config"
  | "promptTemplate"
  | "isActive"
  | "scope"
  | "specRole"
  | "extendsAgent"
  | "isDirty"
  | "dirtyReason"
  | "name"
  | "description"
  | "domain"
  | "priority"
  | "version"
  | "outputType"
  | "specType"
  | "isDeletable"
  | "isArchetype"
>>;

export interface UpdateAnalysisSpecConfigOptions {
  /**
   * Required for DOMAIN-scope specs to identify which Domain row to bump.
   * The schema has no direct `AnalysisSpec.domainId` FK — the calling
   * context (admin tool handler, wizard step, route handler) knows it.
   * If omitted on a DOMAIN-scope write, the bump is skipped with a warning.
   */
  domainId?: string | null;
  /** Skip the timestamp bump (seed / pre-enrolment paths). */
  skipTimestamp?: boolean;
  /**
   * Allow the update to proceed even when the spec is locked. Use only
   * when the caller has performed its own narrower lock check (e.g.
   * the PUT route allows `isActive` toggle on locked specs).
   */
  allowLocked?: boolean;
  /** Diagnostic label for the bump log line. */
  reason?: string;
  /**
   * Recompose fan-out scope for this write. See `update-playbook-config.ts`
   * for the full contract. AI tool executors MUST NOT pass `'all'`.
   *
   * Note: SYSTEM-scope specs have very large blast radius (every active
   * caller across every domain). Treat `'all'` here as load-bearing.
   */
  fanoutScope?: 'none' | 'caller' | 'all';
}

export interface UpdateAnalysisSpecConfigResult {
  spec: AnalysisSpec;
  composeAffectingChanged: boolean;
  timestampBumped: boolean;
  /** What got bumped: "system" | "domain" | "none". */
  bumpTarget: "system" | "domain" | "none";
  /** Echoes the requested fanout scope so callers can branch (default 'none'). */
  fanoutScope: 'none' | 'caller' | 'all';
}

export type AnalysisSpecConfigTransformer = (
  current: AnalysisSpecUpdatable,
) => AnalysisSpecUpdatable;

export async function updateAnalysisSpecConfig(
  specId: string,
  transformer: AnalysisSpecConfigTransformer,
  options: UpdateAnalysisSpecConfigOptions = {},
): Promise<UpdateAnalysisSpecConfigResult> {
  if (!specId) {
    throw new Error("updateAnalysisSpecConfig: specId is required");
  }

  const current = await prisma.analysisSpec.findUnique({
    where: { id: specId },
    select: {
      scope: true,
      config: true,
      promptTemplate: true,
      isActive: true,
      specRole: true,
      extendsAgent: true,
      isLocked: true,
      name: true,
    },
  });
  if (!current) {
    throw new Error(`updateAnalysisSpecConfig: spec ${specId} not found`);
  }
  if (current.isLocked && !options.allowLocked) {
    throw new Error(
      `updateAnalysisSpecConfig: spec ${specId} (${current.name}) is locked`,
    );
  }

  const currentFields: AnalysisSpecUpdatable = {
    config: current.config as AnalysisSpec["config"],
    promptTemplate: current.promptTemplate,
    isActive: current.isActive,
    scope: current.scope,
    specRole: current.specRole,
    extendsAgent: current.extendsAgent,
  };
  const nextFields = transformer(
    JSON.parse(JSON.stringify(currentFields)) as AnalysisSpecUpdatable,
  );

  const composeAffected = composeAffectingSpecChanged(
    currentFields as Record<string, unknown>,
    nextFields as Record<string, unknown>,
  );
  const shouldBumpTimestamp = composeAffected && !options.skipTimestamp;

  const spec = await prisma.analysisSpec.update({
    where: { id: specId },
    data: nextFields as Prisma.AnalysisSpecUpdateInput,
  });

  let bumpTarget: UpdateAnalysisSpecConfigResult["bumpTarget"] = "none";
  let timestampBumped = false;

  if (shouldBumpTimestamp) {
    const effectiveScope: SpecificationScope = (nextFields.scope ??
      current.scope) as SpecificationScope;
    if (effectiveScope === "SYSTEM") {
      const nowIso = new Date().toISOString();
      await prisma.systemSetting.upsert({
        where: { key: SYSTEM_COMPOSE_TIMESTAMP_KEY },
        update: { value: nowIso },
        create: { key: SYSTEM_COMPOSE_TIMESTAMP_KEY, value: nowIso },
      });
      bumpTarget = "system";
      timestampBumped = true;
      console.log(
        `[updateAnalysisSpecConfig] SystemSetting "${SYSTEM_COMPOSE_TIMESTAMP_KEY}" bumped for SYSTEM-scope spec ${specId}${options.reason ? ` (reason: ${options.reason})` : ""}`,
      );
    } else if (effectiveScope === "DOMAIN") {
      if (!options.domainId) {
        console.warn(
          `[updateAnalysisSpecConfig] DOMAIN-scope spec ${specId} updated without options.domainId — Domain.composeInputsUpdatedAt NOT bumped. Cached prompts in this domain will not be marked stale by this write.`,
        );
      } else {
        await prisma.domain.update({
          where: { id: options.domainId },
          data: { composeInputsUpdatedAt: new Date() },
        });
        bumpTarget = "domain";
        timestampBumped = true;
        console.log(
          `[updateAnalysisSpecConfig] Domain.composeInputsUpdatedAt bumped for DOMAIN-scope spec ${specId} → domain ${options.domainId}${options.reason ? ` (reason: ${options.reason})` : ""}`,
        );
      }
    }
    // CALLER scope: no-op (auto-generated specs)
  }

  return {
    spec,
    composeAffectingChanged: composeAffected,
    timestampBumped,
    bumpTarget,
    fanoutScope: options.fanoutScope ?? 'none',
  };
}

export { COMPOSE_AFFECTING_SPEC_FIELDS };
